bicleaner_ai_version: 2.2.1
precision_score: 0.855
recall_score: 0.920
f1_score: 0.887
matthews_corr_coef: 0.874
source_lang: en
target_lang: es
source_lm: model.en-es.en
target_lm: model.en-es.es
lm_type: CHARACTER
clean_mean_perp: -1.0276643779969155
clean_stddev_perp: 0.17795959165002218
noisy_mean_perp: -4.003521114422677
noisy_stddev_perp: 0.1715315750184545
classifier_type: xlmr
classifier_settings:
    activation: relu
    base_model: jplu/tf-xlm-roberta-base
    batch_size: 16
    calibration_params: [8.20954800, -3.15317225]
    epochs: 15
    loss: binary_crossentropy
    maxlen: 150
    model_name: bitextor/bicleaner-ai-full-en-es
    n_classes: 2
    n_hidden: 2048
    patience: 3
    steps_per_epoch: 2000
    warmup_steps: 1000
