no_empty: True
not_too_long: False
not_too_short: False
length_ratio: 3.3
no_identical: False
no_literals: False
no_only_symbols: True
no_only_numbers: False
no_urls: False
no_breadcrumbs: False
no_glued_words: True
no_repeated_words: True
no_unicode_noise: True
no_space_noise: True
no_paren: False
no_escaped_unicode: False
no_bad_encoding: True
no_titles: False
no_wrong_language: True
no_porn: False
no_number_inconsistencies: False
no_script_inconsistencies: False
lm_filter: False
