common:

  output_directory: OpusFilter-output-JW

steps:

  - type: classify
    parameters:
        output_probabilities: ce-JW300.es-en.probabilities.txt
        model: ce_model
        scores: JW300-scores.es-en.jsonl.gz


